from distutils.core import setup
setup(name='oyProjectManager',
      version='10.6.22',
      author='Erkan Ozgur Yilmaz',
      author_email='eoyilmaz@gmail.com',
      packages = [ '',
                   'models',
                   'models.environments',
                   'tests',
                   'ui',
                   'utils'],
      package_dir={'':''},
      package_data={'': ['*.txt','settings/*.xml']},
      #data_files=[('settings',['defaultProjectSettings.xml',
                               #'environmentSettings.xml',
                               #'repositorySettings.xml',
                               #'users.xml'])],
      platforms = ['any'],
      url='http://www.ozgurfx.com',
      license='http://www.opensource.org/licenses/bsd-license.php',
      )
