# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ozgur/Documents/development/oyProjectManager/oyProjectManager/ui/assetManager3.ui'
#
# Created: Mon Nov  7 00:30:31 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(1024, 768)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Asset Manager v0.2.0.a2", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalWidget = QtGui.QWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setObjectName(_fromUtf8("verticalWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, 10, -1, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.projects_label = QtGui.QLabel(self.verticalWidget)
        self.projects_label.setText(QtGui.QApplication.translate("Dialog", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.projects_label.setObjectName(_fromUtf8("projects_label"))
        self.gridLayout_2.addWidget(self.projects_label, 0, 0, 1, 1)
        self.projects_comboBox = QtGui.QComboBox(self.verticalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projects_comboBox.sizePolicy().hasHeightForWidth())
        self.projects_comboBox.setSizePolicy(sizePolicy)
        self.projects_comboBox.setObjectName(_fromUtf8("projects_comboBox"))
        self.gridLayout_2.addWidget(self.projects_comboBox, 1, 0, 1, 1)
        self.user_label = QtGui.QLabel(self.verticalWidget)
        self.user_label.setText(QtGui.QApplication.translate("Dialog", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.user_label.setObjectName(_fromUtf8("user_label"))
        self.gridLayout_2.addWidget(self.user_label, 0, 2, 1, 1)
        self.user_comboBox = QtGui.QComboBox(self.verticalWidget)
        self.user_comboBox.setObjectName(_fromUtf8("user_comboBox"))
        self.gridLayout_2.addWidget(self.user_comboBox, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.tabWidget = QtGui.QTabWidget(self.verticalWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.assets_tab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.assets_tab.sizePolicy().hasHeightForWidth())
        self.assets_tab.setSizePolicy(sizePolicy)
        self.assets_tab.setObjectName(_fromUtf8("assets_tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.assets_tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.asset_info_groupBox = QtGui.QGroupBox(self.assets_tab)
        self.asset_info_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Asset Information", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_info_groupBox.setFlat(False)
        self.asset_info_groupBox.setObjectName(_fromUtf8("asset_info_groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.asset_info_groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.asset_name_label = QtGui.QLabel(self.asset_info_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.asset_name_label.setFont(font)
        self.asset_name_label.setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_name_label.setObjectName(_fromUtf8("asset_name_label"))
        self.horizontalLayout_9.addWidget(self.asset_name_label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.create_asset_pushButton = QtGui.QPushButton(self.asset_info_groupBox)
        self.create_asset_pushButton.setText(QtGui.QApplication.translate("Dialog", "Create New Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.create_asset_pushButton.setObjectName(_fromUtf8("create_asset_pushButton"))
        self.horizontalLayout_9.addWidget(self.create_asset_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.asset_names_listWidget = QtGui.QListWidget(self.asset_info_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asset_names_listWidget.sizePolicy().hasHeightForWidth())
        self.asset_names_listWidget.setSizePolicy(sizePolicy)
        self.asset_names_listWidget.setMinimumSize(QtCore.QSize(180, 0))
        self.asset_names_listWidget.setMaximumSize(QtCore.QSize(180, 16777215))
        self.asset_names_listWidget.setObjectName(_fromUtf8("asset_names_listWidget"))
        self.verticalLayout_2.addWidget(self.asset_names_listWidget)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.thumbnail_label = QtGui.QLabel(self.asset_info_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.thumbnail_label.setFont(font)
        self.thumbnail_label.setText(QtGui.QApplication.translate("Dialog", "Thumbnail", None, QtGui.QApplication.UnicodeUTF8))
        self.thumbnail_label.setObjectName(_fromUtf8("thumbnail_label"))
        self.gridLayout.addWidget(self.thumbnail_label, 0, 1, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.thumbnail_graphicsView = QtGui.QGraphicsView(self.asset_info_groupBox)
        self.thumbnail_graphicsView.setMinimumSize(QtCore.QSize(128, 128))
        self.thumbnail_graphicsView.setMaximumSize(QtCore.QSize(128, 128))
        self.thumbnail_graphicsView.setDragMode(QtGui.QGraphicsView.NoDrag)
        self.thumbnail_graphicsView.setObjectName(_fromUtf8("thumbnail_graphicsView"))
        self.verticalLayout_5.addWidget(self.thumbnail_graphicsView)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.upload_thumbnail_pushButton = QtGui.QPushButton(self.asset_info_groupBox)
        self.upload_thumbnail_pushButton.setText(QtGui.QApplication.translate("Dialog", "Upload\n"
"Thumbnail ...", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_thumbnail_pushButton.setObjectName(_fromUtf8("upload_thumbnail_pushButton"))
        self.verticalLayout_5.addWidget(self.upload_thumbnail_pushButton)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.asset_description_textEdit = QtGui.QTextEdit(self.asset_info_groupBox)
        self.asset_description_textEdit.setEnabled(True)
        self.asset_description_textEdit.setTabChangesFocus(True)
        self.asset_description_textEdit.setReadOnly(True)
        self.asset_description_textEdit.setHtml(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_description_textEdit.setObjectName(_fromUtf8("asset_description_textEdit"))
        self.gridLayout.addWidget(self.asset_description_textEdit, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.asset_description_label = QtGui.QLabel(self.asset_info_groupBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.asset_description_label.setFont(font)
        self.asset_description_label.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_description_label.setObjectName(_fromUtf8("asset_description_label"))
        self.horizontalLayout_7.addWidget(self.asset_description_label)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.asset_description_edit_pushButton = QtGui.QPushButton(self.asset_info_groupBox)
        self.asset_description_edit_pushButton.setText(QtGui.QApplication.translate("Dialog", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_description_edit_pushButton.setCheckable(True)
        self.asset_description_edit_pushButton.setObjectName(_fromUtf8("asset_description_edit_pushButton"))
        self.horizontalLayout_7.addWidget(self.asset_description_edit_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_3.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.asset_info_groupBox)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.new_version_groupBox = QtGui.QGroupBox(self.assets_tab)
        self.new_version_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "New Version", None, QtGui.QApplication.UnicodeUTF8))
        self.new_version_groupBox.setObjectName(_fromUtf8("new_version_groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.new_version_groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.takes_label = QtGui.QLabel(self.new_version_groupBox)
        self.takes_label.setMinimumSize(QtCore.QSize(35, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.takes_label.setFont(font)
        self.takes_label.setText(QtGui.QApplication.translate("Dialog", "Takes", None, QtGui.QApplication.UnicodeUTF8))
        self.takes_label.setObjectName(_fromUtf8("takes_label"))
        self.gridLayout_3.addWidget(self.takes_label, 0, 0, 1, 1)
        self.takes_comboBox = QtGui.QComboBox(self.new_version_groupBox)
        self.takes_comboBox.setEditable(True)
        self.takes_comboBox.setObjectName(_fromUtf8("takes_comboBox"))
        self.gridLayout_3.addWidget(self.takes_comboBox, 0, 1, 1, 1)
        self.version_types_label = QtGui.QLabel(self.new_version_groupBox)
        self.version_types_label.setMinimumSize(QtCore.QSize(35, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.version_types_label.setFont(font)
        self.version_types_label.setText(QtGui.QApplication.translate("Dialog", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.version_types_label.setObjectName(_fromUtf8("version_types_label"))
        self.gridLayout_3.addWidget(self.version_types_label, 1, 0, 1, 1)
        self.types_comboBox = QtGui.QComboBox(self.new_version_groupBox)
        self.types_comboBox.setEditable(True)
        self.types_comboBox.setObjectName(_fromUtf8("types_comboBox"))
        self.gridLayout_3.addWidget(self.types_comboBox, 1, 1, 1, 1)
        self.note_label = QtGui.QLabel(self.new_version_groupBox)
        self.note_label.setMinimumSize(QtCore.QSize(35, 0))
        self.note_label.setText(QtGui.QApplication.translate("Dialog", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.note_label.setObjectName(_fromUtf8("note_label"))
        self.gridLayout_3.addWidget(self.note_label, 3, 0, 1, 1)
        self.version_note_textEdit = QtGui.QTextEdit(self.new_version_groupBox)
        self.version_note_textEdit.setEnabled(True)
        self.version_note_textEdit.setTabChangesFocus(True)
        self.version_note_textEdit.setHtml(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.version_note_textEdit.setObjectName(_fromUtf8("version_note_textEdit"))
        self.gridLayout_3.addWidget(self.version_note_textEdit, 3, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.export_as_pushButton = QtGui.QPushButton(self.new_version_groupBox)
        self.export_as_pushButton.setText(QtGui.QApplication.translate("Dialog", "Export Selection As", None, QtGui.QApplication.UnicodeUTF8))
        self.export_as_pushButton.setObjectName(_fromUtf8("export_as_pushButton"))
        self.horizontalLayout_2.addWidget(self.export_as_pushButton)
        self.save_as_pushButton = QtGui.QPushButton(self.new_version_groupBox)
        self.save_as_pushButton.setText(QtGui.QApplication.translate("Dialog", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.save_as_pushButton.setDefault(True)
        self.save_as_pushButton.setObjectName(_fromUtf8("save_as_pushButton"))
        self.horizontalLayout_2.addWidget(self.save_as_pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10.addWidget(self.new_version_groupBox)
        self.line = QtGui.QFrame(self.assets_tab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_10.addWidget(self.line)
        self.previous_versions_groupBox = QtGui.QGroupBox(self.assets_tab)
        self.previous_versions_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Previous Versions", None, QtGui.QApplication.UnicodeUTF8))
        self.previous_versions_groupBox.setObjectName(_fromUtf8("previous_versions_groupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.previous_versions_groupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.previous_versions_listWidget = QtGui.QListWidget(self.previous_versions_groupBox)
        self.previous_versions_listWidget.setObjectName(_fromUtf8("previous_versions_listWidget"))
        self.verticalLayout_7.addWidget(self.previous_versions_listWidget)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.open_pushButton = QtGui.QPushButton(self.previous_versions_groupBox)
        self.open_pushButton.setText(QtGui.QApplication.translate("Dialog", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.open_pushButton.setObjectName(_fromUtf8("open_pushButton"))
        self.horizontalLayout_5.addWidget(self.open_pushButton)
        self.reference_pushButton = QtGui.QPushButton(self.previous_versions_groupBox)
        self.reference_pushButton.setText(QtGui.QApplication.translate("Dialog", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.reference_pushButton.setObjectName(_fromUtf8("reference_pushButton"))
        self.horizontalLayout_5.addWidget(self.reference_pushButton)
        self.import_pushButton = QtGui.QPushButton(self.previous_versions_groupBox)
        self.import_pushButton.setText(QtGui.QApplication.translate("Dialog", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.import_pushButton.setObjectName(_fromUtf8("import_pushButton"))
        self.horizontalLayout_5.addWidget(self.import_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10.addWidget(self.previous_versions_groupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.assets_tab, _fromUtf8(""))
        self.shots_tab = QtGui.QWidget()
        self.shots_tab.setObjectName(_fromUtf8("shots_tab"))
        self.comboBox_2 = QtGui.QComboBox(self.shots_tab)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 10, 251, 25))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.label_2 = QtGui.QLabel(self.shots_tab)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 71, 21))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.tabWidget.addTab(self.shots_tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.close_pushButton = QtGui.QPushButton(self.verticalWidget)
        self.close_pushButton.setStyleSheet(_fromUtf8(""))
        self.close_pushButton.setText(QtGui.QApplication.translate("Dialog", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.close_pushButton.setDefault(False)
        self.close_pushButton.setFlat(False)
        self.close_pushButton.setObjectName(_fromUtf8("close_pushButton"))
        self.horizontalLayout_8.addWidget(self.close_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout.addWidget(self.verticalWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.projects_comboBox, self.user_comboBox)
        Dialog.setTabOrder(self.user_comboBox, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.create_asset_pushButton)
        Dialog.setTabOrder(self.create_asset_pushButton, self.asset_names_listWidget)
        Dialog.setTabOrder(self.asset_names_listWidget, self.asset_description_edit_pushButton)
        Dialog.setTabOrder(self.asset_description_edit_pushButton, self.asset_description_textEdit)
        Dialog.setTabOrder(self.asset_description_textEdit, self.thumbnail_graphicsView)
        Dialog.setTabOrder(self.thumbnail_graphicsView, self.upload_thumbnail_pushButton)
        Dialog.setTabOrder(self.upload_thumbnail_pushButton, self.takes_comboBox)
        Dialog.setTabOrder(self.takes_comboBox, self.types_comboBox)
        Dialog.setTabOrder(self.types_comboBox, self.version_note_textEdit)
        Dialog.setTabOrder(self.version_note_textEdit, self.export_as_pushButton)
        Dialog.setTabOrder(self.export_as_pushButton, self.save_as_pushButton)
        Dialog.setTabOrder(self.save_as_pushButton, self.previous_versions_listWidget)
        Dialog.setTabOrder(self.previous_versions_listWidget, self.open_pushButton)
        Dialog.setTabOrder(self.open_pushButton, self.reference_pushButton)
        Dialog.setTabOrder(self.reference_pushButton, self.import_pushButton)
        Dialog.setTabOrder(self.import_pushButton, self.close_pushButton)
        Dialog.setTabOrder(self.close_pushButton, self.comboBox_2)

    def retranslateUi(self, Dialog):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.assets_tab), QtGui.QApplication.translate("Dialog", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shots_tab), QtGui.QApplication.translate("Dialog", "Shots", None, QtGui.QApplication.UnicodeUTF8))

