# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ozgur/maya/scripts/oy-maya-scripts/oyTools/oyProjectManager/ui/assetManager2.ui'
#
# Created: Fri Jul  9 02:35:37 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(1002, 877)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_horizontalWidget = QtGui.QWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.main_horizontalWidget.sizePolicy().hasHeightForWidth())
        self.main_horizontalWidget.setSizePolicy(sizePolicy)
        self.main_horizontalWidget.setObjectName("main_horizontalWidget")
        self.main_horizontalLayout = QtGui.QHBoxLayout(self.main_horizontalWidget)
        self.main_horizontalLayout.setMargin(6)
        self.main_horizontalLayout.setObjectName("main_horizontalLayout")
        self.verticalWidget1 = QtGui.QWidget(self.main_horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.verticalWidget1.sizePolicy().hasHeightForWidth())
        self.verticalWidget1.setSizePolicy(sizePolicy)
        self.verticalWidget1.setObjectName("verticalWidget1")
        self.verticalLayout1 = QtGui.QVBoxLayout(self.verticalWidget1)
        self.verticalLayout1.setMargin(0)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.saveAsset_groupBox = QtGui.QGroupBox(self.verticalWidget1)
        self.saveAsset_groupBox.setObjectName("saveAsset_groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.saveAsset_groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.saveButtons_horizontalWidget = QtGui.QWidget(self.saveAsset_groupBox)
        self.saveButtons_horizontalWidget.setObjectName("saveButtons_horizontalWidget")
        self.saveCanel_horizontalLayout = QtGui.QHBoxLayout(self.saveButtons_horizontalWidget)
        self.saveCanel_horizontalLayout.setObjectName("saveCanel_horizontalLayout")
        self.save_button = QtGui.QPushButton(self.saveButtons_horizontalWidget)
        self.save_button.setObjectName("save_button")
        self.saveCanel_horizontalLayout.addWidget(self.save_button)
        self.export_button = QtGui.QPushButton(self.saveButtons_horizontalWidget)
        self.export_button.setObjectName("export_button")
        self.saveCanel_horizontalLayout.addWidget(self.export_button)
        self.saveCanel_horizontalLayout.setStretch(0, 1)
        self.saveCanel_horizontalLayout.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.saveButtons_horizontalWidget)
        self.verticalLayout1.addWidget(self.saveAsset_groupBox)
        self.main_horizontalLayout.addWidget(self.verticalWidget1)
        self.verticalWidget2 = QtGui.QWidget(self.main_horizontalWidget)
        self.verticalWidget2.setObjectName("verticalWidget2")
        self.verticalLayout2 = QtGui.QVBoxLayout(self.verticalWidget2)
        self.verticalLayout2.setMargin(0)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.shotData_groupBox = QtGui.QGroupBox(self.verticalWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.shotData_groupBox.sizePolicy().hasHeightForWidth())
        self.shotData_groupBox.setSizePolicy(sizePolicy)
        self.shotData_groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.shotData_groupBox.setObjectName("shotData_groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.shotData_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalWidget = QtGui.QWidget(self.shotData_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameRange_label = QtGui.QLabel(self.horizontalWidget)
        self.frameRange_label.setObjectName("frameRange_label")
        self.horizontalLayout_2.addWidget(self.frameRange_label)
        self.line_7 = QtGui.QFrame(self.horizontalWidget)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_2.addWidget(self.line_7)
        self.startFrame_label = QtGui.QLabel(self.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startFrame_label.sizePolicy().hasHeightForWidth())
        self.startFrame_label.setSizePolicy(sizePolicy)
        self.startFrame_label.setObjectName("startFrame_label")
        self.horizontalLayout_2.addWidget(self.startFrame_label)
        self.startFrame_spinBox = QtGui.QSpinBox(self.horizontalWidget)
        self.startFrame_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startFrame_spinBox.sizePolicy().hasHeightForWidth())
        self.startFrame_spinBox.setSizePolicy(sizePolicy)
        self.startFrame_spinBox.setMaximum(999999999)
        self.startFrame_spinBox.setObjectName("startFrame_spinBox")
        self.horizontalLayout_2.addWidget(self.startFrame_spinBox)
        self.endFrame_label = QtGui.QLabel(self.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endFrame_label.sizePolicy().hasHeightForWidth())
        self.endFrame_label.setSizePolicy(sizePolicy)
        self.endFrame_label.setObjectName("endFrame_label")
        self.horizontalLayout_2.addWidget(self.endFrame_label)
        self.endFrame_spinBox = QtGui.QSpinBox(self.horizontalWidget)
        self.endFrame_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endFrame_spinBox.sizePolicy().hasHeightForWidth())
        self.endFrame_spinBox.setSizePolicy(sizePolicy)
        self.endFrame_spinBox.setMaximum(999999999)
        self.endFrame_spinBox.setObjectName("endFrame_spinBox")
        self.horizontalLayout_2.addWidget(self.endFrame_spinBox)
        self.verticalLayout_2.addWidget(self.horizontalWidget)
        self.shotDescription_label = QtGui.QLabel(self.shotData_groupBox)
        self.shotDescription_label.setObjectName("shotDescription_label")
        self.verticalLayout_2.addWidget(self.shotDescription_label)
        self.shotDescription_textEdit = QtGui.QTextEdit(self.shotData_groupBox)
        self.shotDescription_textEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.shotDescription_textEdit.sizePolicy().hasHeightForWidth())
        self.shotDescription_textEdit.setSizePolicy(sizePolicy)
        self.shotDescription_textEdit.setObjectName("shotDescription_textEdit")
        self.verticalLayout_2.addWidget(self.shotDescription_textEdit)
        self.verticalLayout2.addWidget(self.shotData_groupBox)
        self.open_groupBox = QtGui.QGroupBox(self.verticalWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.open_groupBox.sizePolicy().hasHeightForWidth())
        self.open_groupBox.setSizePolicy(sizePolicy)
        self.open_groupBox.setObjectName("open_groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.open_groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalWidget_2 = QtGui.QWidget(self.open_groupBox)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showLastNEntry_checkBox = QtGui.QCheckBox(self.horizontalWidget_2)
        self.showLastNEntry_checkBox.setChecked(True)
        self.showLastNEntry_checkBox.setObjectName("showLastNEntry_checkBox")
        self.horizontalLayout.addWidget(self.showLastNEntry_checkBox)
        self.numberOfEntry_spinBox = QtGui.QSpinBox(self.horizontalWidget_2)
        self.numberOfEntry_spinBox.setMinimum(1)
        self.numberOfEntry_spinBox.setMaximum(9999999)
        self.numberOfEntry_spinBox.setObjectName("numberOfEntry_spinBox")
        self.horizontalLayout.addWidget(self.numberOfEntry_spinBox)
        self.label = QtGui.QLabel(self.horizontalWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.horizontalWidget_2)
        self.assets_tableWidget1 = QtGui.QTableWidget(self.open_groupBox)
        self.assets_tableWidget1.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.assets_tableWidget1.setAlternatingRowColors(True)
        self.assets_tableWidget1.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.assets_tableWidget1.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.assets_tableWidget1.setShowGrid(False)
        self.assets_tableWidget1.setGridStyle(QtCore.Qt.NoPen)
        self.assets_tableWidget1.setColumnCount(3)
        self.assets_tableWidget1.setObjectName("assets_tableWidget1")
        self.assets_tableWidget1.setColumnCount(3)
        self.assets_tableWidget1.setRowCount(0)
        self.assets_tableWidget1.horizontalHeader().setStretchLastSection(True)
        self.assets_tableWidget1.verticalHeader().setVisible(False)
        self.assets_tableWidget1.verticalHeader().setDefaultSectionSize(19)
        self.verticalLayout_4.addWidget(self.assets_tableWidget1)
        self.horizontalWidget1 = QtGui.QWidget(self.open_groupBox)
        self.horizontalWidget1.setObjectName("horizontalWidget1")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalWidget1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadSettings_label = QtGui.QLabel(self.horizontalWidget1)
        self.loadSettings_label.setObjectName("loadSettings_label")
        self.horizontalLayout_3.addWidget(self.loadSettings_label)
        self.loadSettings_comboBox = QtGui.QComboBox(self.horizontalWidget1)
        self.loadSettings_comboBox.setObjectName("loadSettings_comboBox")
        self.horizontalLayout_3.addWidget(self.loadSettings_comboBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.horizontalWidget1)
        self.openButtons_horizontalWidget = QtGui.QWidget(self.open_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButtons_horizontalWidget.sizePolicy().hasHeightForWidth())
        self.openButtons_horizontalWidget.setSizePolicy(sizePolicy)
        self.openButtons_horizontalWidget.setObjectName("openButtons_horizontalWidget")
        self.openButtons_horizontalLayout = QtGui.QHBoxLayout(self.openButtons_horizontalWidget)
        self.openButtons_horizontalLayout.setObjectName("openButtons_horizontalLayout")
        self.open_button = QtGui.QPushButton(self.openButtons_horizontalWidget)
        self.open_button.setObjectName("open_button")
        self.openButtons_horizontalLayout.addWidget(self.open_button)
        self.reference_button = QtGui.QPushButton(self.openButtons_horizontalWidget)
        self.reference_button.setObjectName("reference_button")
        self.openButtons_horizontalLayout.addWidget(self.reference_button)
        self.import_button = QtGui.QPushButton(self.openButtons_horizontalWidget)
        self.import_button.setObjectName("import_button")
        self.openButtons_horizontalLayout.addWidget(self.import_button)
        self.close_button = QtGui.QPushButton(self.openButtons_horizontalWidget)
        self.close_button.setObjectName("close_button")
        self.openButtons_horizontalLayout.addWidget(self.close_button)
        self.openButtons_horizontalLayout.setStretch(0, 1)
        self.openButtons_horizontalLayout.setStretch(1, 1)
        self.openButtons_horizontalLayout.setStretch(2, 1)
        self.openButtons_horizontalLayout.setStretch(3, 1)
        self.verticalLayout_4.addWidget(self.openButtons_horizontalWidget)
        self.verticalLayout2.addWidget(self.open_groupBox)
        self.main_horizontalLayout.addWidget(self.verticalWidget2)
        self.main_horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addWidget(self.main_horizontalWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.save_button, self.export_button)
        Dialog.setTabOrder(self.export_button, self.startFrame_spinBox)
        Dialog.setTabOrder(self.startFrame_spinBox, self.endFrame_spinBox)
        Dialog.setTabOrder(self.endFrame_spinBox, self.shotDescription_textEdit)
        Dialog.setTabOrder(self.shotDescription_textEdit, self.showLastNEntry_checkBox)
        Dialog.setTabOrder(self.showLastNEntry_checkBox, self.numberOfEntry_spinBox)
        Dialog.setTabOrder(self.numberOfEntry_spinBox, self.assets_tableWidget1)
        Dialog.setTabOrder(self.assets_tableWidget1, self.loadSettings_comboBox)
        Dialog.setTabOrder(self.loadSettings_comboBox, self.open_button)
        Dialog.setTabOrder(self.open_button, self.reference_button)
        Dialog.setTabOrder(self.reference_button, self.import_button)
        Dialog.setTabOrder(self.import_button, self.close_button)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Asset Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsset_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Save Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setToolTip(QtGui.QApplication.translate("Dialog", "Saves the asset to the server", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setStatusTip(QtGui.QApplication.translate("Dialog", "Saves the asset to the server", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setWhatsThis(QtGui.QApplication.translate("Dialog", "Save:\n"
"\n"
"Saves the asset to the server", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.export_button.setToolTip(QtGui.QApplication.translate("Dialog", "Exports the Selected items as a new asset", None, QtGui.QApplication.UnicodeUTF8))
        self.export_button.setStatusTip(QtGui.QApplication.translate("Dialog", "Exports the Selected items as a new asset", None, QtGui.QApplication.UnicodeUTF8))
        self.export_button.setWhatsThis(QtGui.QApplication.translate("Dialog", "Export:\n"
"\n"
"Exports the selected content to the server as an asset", None, QtGui.QApplication.UnicodeUTF8))
        self.export_button.setText(QtGui.QApplication.translate("Dialog", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.shotData_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Shot Data", None, QtGui.QApplication.UnicodeUTF8))
        self.frameRange_label.setText(QtGui.QApplication.translate("Dialog", "Frame Range", None, QtGui.QApplication.UnicodeUTF8))
        self.startFrame_label.setText(QtGui.QApplication.translate("Dialog", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.endFrame_label.setText(QtGui.QApplication.translate("Dialog", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.shotDescription_label.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.open_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Open Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.showLastNEntry_checkBox.setToolTip(QtGui.QApplication.translate("Dialog", "if checked, the list below shows maximum n number of items, the n is defined in the next spinB,ox", None, QtGui.QApplication.UnicodeUTF8))
        self.showLastNEntry_checkBox.setStatusTip(QtGui.QApplication.translate("Dialog", "maximum number of entry to view", None, QtGui.QApplication.UnicodeUTF8))
        self.showLastNEntry_checkBox.setText(QtGui.QApplication.translate("Dialog", "Show Last", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfEntry_spinBox.setStatusTip(QtGui.QApplication.translate("Dialog", "maximum number of entry to view", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setStatusTip(QtGui.QApplication.translate("Dialog", "maximum number of entry to view", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "entry", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSettings_label.setText(QtGui.QApplication.translate("Dialog", "Load Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.open_button.setToolTip(QtGui.QApplication.translate("Dialog", "Opens the selected asset", None, QtGui.QApplication.UnicodeUTF8))
        self.open_button.setStatusTip(QtGui.QApplication.translate("Dialog", "Opens the selected asset", None, QtGui.QApplication.UnicodeUTF8))
        self.open_button.setWhatsThis(QtGui.QApplication.translate("Dialog", "Open:\n"
"\n"
"Opens the current selected asset in the host application", None, QtGui.QApplication.UnicodeUTF8))
        self.open_button.setText(QtGui.QApplication.translate("Dialog", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.reference_button.setToolTip(QtGui.QApplication.translate("Dialog", "References the asset tho the current scene (Maya only)", None, QtGui.QApplication.UnicodeUTF8))
        self.reference_button.setStatusTip(QtGui.QApplication.translate("Dialog", "References the asset tho the current scene (Maya only)", None, QtGui.QApplication.UnicodeUTF8))
        self.reference_button.setWhatsThis(QtGui.QApplication.translate("Dialog", "Reference:\n"
"\n"
"References the asset to the current environment in the host application. For now just MAYA supports referencing, but in near future NUKE will have too...", None, QtGui.QApplication.UnicodeUTF8))
        self.reference_button.setText(QtGui.QApplication.translate("Dialog", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.import_button.setToolTip(QtGui.QApplication.translate("Dialog", "Imports the contents to the current scene", None, QtGui.QApplication.UnicodeUTF8))
        self.import_button.setStatusTip(QtGui.QApplication.translate("Dialog", "Imports the contents to the current scene", None, QtGui.QApplication.UnicodeUTF8))
        self.import_button.setWhatsThis(QtGui.QApplication.translate("Dialog", "Import:\n"
"\n"
"Imports the content of the selected asset to the current environment in the host application...", None, QtGui.QApplication.UnicodeUTF8))
        self.import_button.setText(QtGui.QApplication.translate("Dialog", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setToolTip(QtGui.QApplication.translate("Dialog", "Quits without doing anything", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setStatusTip(QtGui.QApplication.translate("Dialog", "Quits without doing anything", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setWhatsThis(QtGui.QApplication.translate("Dialog", "Cancel:\n"
"\n"
"Just quits the application without doing anything", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setText(QtGui.QApplication.translate("Dialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

