# -*- coding: utf-8 -*-



from PyQt4 import QtCore, QtGui






class AssetCreator(object):
    def __init__(self, parent):
        self.gridWidget1 = QtGui.QWidget( parent )
        #self.gridWidget1.setGeometry(QtCore.QRect(8, 23, 345, 781))
        self.gridWidget1.setObjectName("gridWidget1")
        self.gridLayout1 = QtGui.QGridLayout(self.gridWidget1)
        self.gridLayout1.setObjectName("gridLayout1")
        self.shot_label1 = QtGui.QLabel(self.gridWidget1)
        self.shot_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shot_label1.setObjectName("shot_label1")
        self.gridLayout1.addWidget(self.shot_label1, 7, 0, 1, 1)
        self.server_label = QtGui.QLabel(self.gridWidget1)
        self.server_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.server_label.setObjectName("server_label")
        self.gridLayout1.addWidget(self.server_label, 0, 0, 1, 1)
        self.revision_label1 = QtGui.QLabel(self.gridWidget1)
        self.revision_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.revision_label1.setObjectName("revision_label1")
        self.gridLayout1.addWidget(self.revision_label1, 16, 0, 1, 1)
        self.version_horizontalWidget = QtGui.QWidget(self.gridWidget1)
        self.version_horizontalWidget.setObjectName("version_horizontalWidget")
        self.version_horizontalLayout = QtGui.QHBoxLayout(self.version_horizontalWidget)
        self.version_horizontalLayout.setMargin(0)
        self.version_horizontalLayout.setObjectName("version_horizontalLayout")
        self.version_spinBox = QtGui.QSpinBox(self.version_horizontalWidget)
        self.version_spinBox.setPrefix("")
        self.version_spinBox.setMinimum(1)
        self.version_spinBox.setMaximum(99999999)
        self.version_spinBox.setObjectName("version_spinBox")
        self.version_horizontalLayout.addWidget(self.version_spinBox)
        self.version_pushButton = QtGui.QPushButton(self.version_horizontalWidget)
        self.version_pushButton.setMinimumSize(QtCore.QSize(111, 0))
        self.version_pushButton.setObjectName("version_pushButton")
        self.version_horizontalLayout.addWidget(self.version_pushButton)
        self.gridLayout1.addWidget(self.version_horizontalWidget, 17, 1, 1, 1)
        self.shot_comboBox1 = QtGui.QComboBox(self.gridWidget1)
        self.shot_comboBox1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_comboBox1.sizePolicy().hasHeightForWidth())
        self.shot_comboBox1.setSizePolicy(sizePolicy)
        self.shot_comboBox1.setObjectName("shot_comboBox1")
        self.gridLayout1.addWidget(self.shot_comboBox1, 7, 1, 1, 1)
        self.sequence_label = QtGui.QLabel(self.gridWidget1)
        self.sequence_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sequence_label.setObjectName("sequence_label")
        self.gridLayout1.addWidget(self.sequence_label, 3, 0, 1, 1)
        self.subName_listWidget = QtGui.QListWidget(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.subName_listWidget.sizePolicy().hasHeightForWidth())
        self.subName_listWidget.setSizePolicy(sizePolicy)
        self.subName_listWidget.setAlternatingRowColors(True)
        self.subName_listWidget.setResizeMode(QtGui.QListView.Fixed)
        self.subName_listWidget.setObjectName("subName_listWidget")
        self.gridLayout1.addWidget(self.subName_listWidget, 13, 1, 1, 1)
        self.server_comboBox = QtGui.QComboBox(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_comboBox.sizePolicy().hasHeightForWidth())
        self.server_comboBox.setSizePolicy(sizePolicy)
        self.server_comboBox.setEditable(False)
        self.server_comboBox.setObjectName("server_comboBox")
        self.gridLayout1.addWidget(self.server_comboBox, 0, 1, 1, 1)
        self.note_lineEdit1 = QtGui.QLineEdit(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.note_lineEdit1.sizePolicy().hasHeightForWidth())
        self.note_lineEdit1.setSizePolicy(sizePolicy)
        self.note_lineEdit1.setObjectName("note_lineEdit1")
        self.gridLayout1.addWidget(self.note_lineEdit1, 19, 1, 1, 1)
        self.revision_horizontalWidget = QtGui.QWidget(self.gridWidget1)
        self.revision_horizontalWidget.setObjectName("revision_horizontalWidget")
        self.revision_horizontalLayout = QtGui.QHBoxLayout(self.revision_horizontalWidget)
        self.revision_horizontalLayout.setMargin(0)
        self.revision_horizontalLayout.setObjectName("revision_horizontalLayout")
        self.revision_spinBox = QtGui.QSpinBox(self.revision_horizontalWidget)
        self.revision_spinBox.setObjectName("revision_spinBox")
        self.revision_horizontalLayout.addWidget(self.revision_spinBox)
        self.revision_pushButton = QtGui.QPushButton(self.revision_horizontalWidget)
        self.revision_pushButton.setMinimumSize(QtCore.QSize(111, 0))
        self.revision_pushButton.setObjectName("revision_pushButton")
        self.revision_horizontalLayout.addWidget(self.revision_pushButton)
        self.revision_horizontalLayout.setStretch(0, 1)
        self.revision_horizontalLayout.setStretch(1, 1)
        self.gridLayout1.addWidget(self.revision_horizontalWidget, 16, 1, 1, 1)
        self.assetType_label1 = QtGui.QLabel(self.gridWidget1)
        self.assetType_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.assetType_label1.setObjectName("assetType_label1")
        self.gridLayout1.addWidget(self.assetType_label1, 6, 0, 1, 1)
        self.baseName_listWidget = QtGui.QListWidget(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.baseName_listWidget.sizePolicy().hasHeightForWidth())
        self.baseName_listWidget.setSizePolicy(sizePolicy)
        self.baseName_listWidget.setAlternatingRowColors(True)
        self.baseName_listWidget.setObjectName("baseName_listWidget")
        self.gridLayout1.addWidget(self.baseName_listWidget, 10, 1, 1, 1)
        self.assetType_comboBox1 = QtGui.QComboBox(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assetType_comboBox1.sizePolicy().hasHeightForWidth())
        self.assetType_comboBox1.setSizePolicy(sizePolicy)
        self.assetType_comboBox1.setObjectName("assetType_comboBox1")
        self.gridLayout1.addWidget(self.assetType_comboBox1, 6, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.gridWidget1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout1.addWidget(self.line_4, 12, 0, 1, 2)
        self.line = QtGui.QFrame(self.gridWidget1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout1.addWidget(self.line, 1, 0, 1, 2)
        self.project_comboBox = QtGui.QComboBox(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_comboBox.sizePolicy().hasHeightForWidth())
        self.project_comboBox.setSizePolicy(sizePolicy)
        self.project_comboBox.setEditable(False)
        self.project_comboBox.setObjectName("project_comboBox")
        self.gridLayout1.addWidget(self.project_comboBox, 2, 1, 1, 1)
        self.subName_label1 = QtGui.QLabel(self.gridWidget1)
        self.subName_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.subName_label1.setObjectName("subName_label1")
        self.gridLayout1.addWidget(self.subName_label1, 13, 0, 1, 1)
        self.note_label1 = QtGui.QLabel(self.gridWidget1)
        self.note_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.note_label1.setObjectName("note_label1")
        self.gridLayout1.addWidget(self.note_label1, 19, 0, 1, 1)
        self.baseName_label1 = QtGui.QLabel(self.gridWidget1)
        self.baseName_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.baseName_label1.setObjectName("baseName_label1")
        self.gridLayout1.addWidget(self.baseName_label1, 10, 0, 1, 1)
        self.sequence_comboBox = QtGui.QComboBox(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_comboBox.sizePolicy().hasHeightForWidth())
        self.sequence_comboBox.setSizePolicy(sizePolicy)
        self.sequence_comboBox.setEditable(False)
        self.sequence_comboBox.setObjectName("sequence_comboBox")
        self.gridLayout1.addWidget(self.sequence_comboBox, 3, 1, 1, 1)
        self.baseName_lineEdit = QtGui.QLineEdit(self.gridWidget1)
        self.baseName_lineEdit.setObjectName("baseName_lineEdit")
        self.gridLayout1.addWidget(self.baseName_lineEdit, 11, 1, 1, 1)
        self.project_label = QtGui.QLabel(self.gridWidget1)
        self.project_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.project_label.setObjectName("project_label")
        self.gridLayout1.addWidget(self.project_label, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.gridWidget1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout1.addWidget(self.line_2, 4, 0, 1, 2)
        self.line_5 = QtGui.QFrame(self.gridWidget1)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout1.addWidget(self.line_5, 15, 0, 1, 2)
        self.line_3 = QtGui.QFrame(self.gridWidget1)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout1.addWidget(self.line_3, 8, 0, 1, 2)
        self.subName_lineEdit = QtGui.QLineEdit(self.gridWidget1)
        self.subName_lineEdit.setObjectName("subName_lineEdit")
        self.gridLayout1.addWidget(self.subName_lineEdit, 14, 1, 1, 1)
        self.user_comboBox1 = QtGui.QComboBox(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_comboBox1.sizePolicy().hasHeightForWidth())
        self.user_comboBox1.setSizePolicy(sizePolicy)
        self.user_comboBox1.setObjectName("user_comboBox1")
        self.gridLayout1.addWidget(self.user_comboBox1, 18, 1, 1, 1)
        self.user_label1 = QtGui.QLabel(self.gridWidget1)
        self.user_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.user_label1.setObjectName("user_label1")
        self.gridLayout1.addWidget(self.user_label1, 18, 0, 1, 1)
        self.version_label1 = QtGui.QLabel(self.gridWidget1)
        self.version_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_label1.setObjectName("version_label1")
        self.gridLayout1.addWidget(self.version_label1, 17, 0, 1, 1)
        self.formats_comboBox = QtGui.QComboBox(self.gridWidget1)
        self.formats_comboBox.setObjectName("formats_comboBox")
        self.gridLayout1.addWidget(self.formats_comboBox, 20, 1, 1, 1)
        self.formats_label = QtGui.QLabel(self.gridWidget1)
        self.formats_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formats_label.setObjectName("formats_label")
        self.gridLayout1.addWidget(self.formats_label, 20, 0, 1, 1)
        
        assert(isinstance(parent, QtGui.QGroupBox))
        self.gridWidget1.layout().setSizeConstraint( QtGui.QLayout.SetMinimumSize )
        parent.layout().setSizeConstraint( QtGui.QLayout.SetMinimumSize )
        parent.parent().layout().setSizeConstraint( QtGui.QLayout.SetMinimumSize )
        parent.parent().parent().layout().setSizeConstraint( QtGui.QLayout.SetMinimumSize )
        parent.parent().parent().parent().layout().setSizeConstraint( QtGui.QLayout.SetMinimumSize )
        

        #parent.setSizePolicy( QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred )
        #self.gridWidget1.setSizePolicy( QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum )

        
        #self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(parent)
        

    #def retranslateUi(self, Dialog):
        ##Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        #self.shot_label1.setText(QtGui.QApplication.translate("Dialog", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        #self.server_label.setText(QtGui.QApplication.translate("Dialog", "Server", None, QtGui.QApplication.UnicodeUTF8))
        #self.revision_label1.setText(QtGui.QApplication.translate("Dialog", "Revision", None, QtGui.QApplication.UnicodeUTF8))
        #self.version_spinBox.setToolTip(QtGui.QApplication.translate("Dialog", "it is automatically increased by 1", None, QtGui.QApplication.UnicodeUTF8))
        #self.version_spinBox.setStatusTip(QtGui.QApplication.translate("Dialog", "it is automatically increased by 1", None, QtGui.QApplication.UnicodeUTF8))
        #self.version_spinBox.setWhatsThis(QtGui.QApplication.translate("Dialog", "Version Number:\n"
#"\n"
#"Any incarnation of an asset should be have different version numbers.", None, QtGui.QApplication.UnicodeUTF8))
        #self.version_pushButton.setToolTip(QtGui.QApplication.translate("Dialog", "gets the latest version number", None, QtGui.QApplication.UnicodeUTF8))
        #self.version_pushButton.setStatusTip(QtGui.QApplication.translate("Dialog", "gets the latest version number", None, QtGui.QApplication.UnicodeUTF8))
        #self.version_pushButton.setText(QtGui.QApplication.translate("Dialog", "Latest Version", None, QtGui.QApplication.UnicodeUTF8))
        #self.shot_comboBox1.setToolTip(QtGui.QApplication.translate("Dialog", "if the type is a shot dependent type this will be activated", None, QtGui.QApplication.UnicodeUTF8))
        #self.shot_comboBox1.setStatusTip(QtGui.QApplication.translate("Dialog", "if the type is a shot dependent type this will be activated", None, QtGui.QApplication.UnicodeUTF8))
        #self.shot_comboBox1.setWhatsThis(QtGui.QApplication.translate("Dialog", "Shot:\n"
#"\n"
#"If an asset is shot dependent, its base name is a shot string (SH001, SH010 etc. ). So, shot and base name comboBoxes are actually showing the base name of the asset, but it lets the user to separate the shot dependent asset types from shot independent types.", None, QtGui.QApplication.UnicodeUTF8))
        #self.sequence_label.setText(QtGui.QApplication.translate("Dialog", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        #self.subName_listWidget.setToolTip(QtGui.QApplication.translate("Dialog", "displays the subNames of the current asset", None, QtGui.QApplication.UnicodeUTF8))
        #self.subName_listWidget.setStatusTip(QtGui.QApplication.translate("Dialog", "displays the subNames of the current asset", None, QtGui.QApplication.UnicodeUTF8))
        #self.server_comboBox.setToolTip(QtGui.QApplication.translate("Dialog", "Select a Server", None, QtGui.QApplication.UnicodeUTF8))
        #self.server_comboBox.setStatusTip(QtGui.QApplication.translate("Dialog", "Select a Server", None, QtGui.QApplication.UnicodeUTF8))
        #self.server_comboBox.setWhatsThis(QtGui.QApplication.translate("Dialog", "Server:\n"
#"\n"
#"Servers are the places that the main project folders are saved. For now there is only one supported server. In the future that can be expanded to multiple servers...", None, QtGui.QApplication.UnicodeUTF8))
        #self.note_lineEdit1.setToolTip(QtGui.QApplication.translate("Dialog", "it is a limited field, try to keep it brief", None, QtGui.QApplication.UnicodeUTF8))
        #self.note_lineEdit1.setStatusTip(QtGui.QApplication.translate("Dialog", "it is a limited field, try to keep it brief", None, QtGui.QApplication.UnicodeUTF8))
        #self.note_lineEdit1.setWhatsThis(QtGui.QApplication.translate("Dialog", "Note:\n"
#"\n"
#"You can use this field to leave little but important messages here... It is limited with 30 characters...", None, QtGui.QApplication.UnicodeUTF8))
        #self.revision_spinBox.setToolTip(QtGui.QApplication.translate("Dialog", "increase it when the asset needs a revision", None, QtGui.QApplication.UnicodeUTF8))
        #self.revision_spinBox.setStatusTip(QtGui.QApplication.translate("Dialog", "increase it when the asset needs a revision", None, QtGui.QApplication.UnicodeUTF8))
        #self.revision_spinBox.setWhatsThis(QtGui.QApplication.translate("Dialog", "Revision Number:\n"
#"\n"
#"Revision numbers represents the milestones in the development of this asset. Generally it is increased when something big is changed in the asset.", None, QtGui.QApplication.UnicodeUTF8))
        #self.revision_pushButton.setToolTip(QtGui.QApplication.translate("Dialog", "gets the latest revision number", None, QtGui.QApplication.UnicodeUTF8))
        #self.revision_pushButton.setStatusTip(QtGui.QApplication.translate("Dialog", "gets the latest revision number", None, QtGui.QApplication.UnicodeUTF8))
        #self.revision_pushButton.setText(QtGui.QApplication.translate("Dialog", "Lastest Revision", None, QtGui.QApplication.UnicodeUTF8))
        #self.assetType_label1.setText(QtGui.QApplication.translate("Dialog", "Asset Type", None, QtGui.QApplication.UnicodeUTF8))
        #self.baseName_listWidget.setToolTip(QtGui.QApplication.translate("Dialog", "displays the baseNames of the current assetType", None, QtGui.QApplication.UnicodeUTF8))
        #self.baseName_listWidget.setStatusTip(QtGui.QApplication.translate("Dialog", "displays the baseNames of the current assetType", None, QtGui.QApplication.UnicodeUTF8))
        #self.assetType_comboBox1.setToolTip(QtGui.QApplication.translate("Dialog", "Select an asset type", None, QtGui.QApplication.UnicodeUTF8))
        #self.assetType_comboBox1.setStatusTip(QtGui.QApplication.translate("Dialog", "Select an asset type", None, QtGui.QApplication.UnicodeUTF8))
        #self.assetType_comboBox1.setWhatsThis(QtGui.QApplication.translate("Dialog", "Asset Type:\n"
#"\n"
#"Assets has types that lets you distinguish their purpose of existance. This comboBox lists the asset types that the sequence and the current host environment (MAYA, NUKE etc.) can support.", None, QtGui.QApplication.UnicodeUTF8))
        #self.project_comboBox.setToolTip(QtGui.QApplication.translate("Dialog", "Select a Project", None, QtGui.QApplication.UnicodeUTF8))
        #self.project_comboBox.setStatusTip(QtGui.QApplication.translate("Dialog", "Select a Project", None, QtGui.QApplication.UnicodeUTF8))
        #self.project_comboBox.setWhatsThis(QtGui.QApplication.translate("Dialog", "Project:\n"
#"\n"
#"A project is a collection of sequences. So projects can only contain sequences. This comboBox lists the current projects on the server. If you select one it will update the available sequences for that project...", None, QtGui.QApplication.UnicodeUTF8))
        #self.subName_label1.setText(QtGui.QApplication.translate("Dialog", "Sub Name", None, QtGui.QApplication.UnicodeUTF8))
        #self.note_label1.setText(QtGui.QApplication.translate("Dialog", "Note", None, QtGui.QApplication.UnicodeUTF8))
        #self.baseName_label1.setText(QtGui.QApplication.translate("Dialog", "Base Name", None, QtGui.QApplication.UnicodeUTF8))
        #self.sequence_comboBox.setToolTip(QtGui.QApplication.translate("Dialog", "Select a Sequence", None, QtGui.QApplication.UnicodeUTF8))
        #self.sequence_comboBox.setStatusTip(QtGui.QApplication.translate("Dialog", "Select a Sequence", None, QtGui.QApplication.UnicodeUTF8))
        #self.sequence_comboBox.setWhatsThis(QtGui.QApplication.translate("Dialog", "Sequence:\n"
#"\n"
#"Sequences are collections of folders. Each folder has a special meaning and can may contain one type of asset file. Every sequence has its own settings. So while one sequence supports some features, others may not...", None, QtGui.QApplication.UnicodeUTF8))
        #self.baseName_lineEdit.setToolTip(QtGui.QApplication.translate("Dialog", "enter the baseName for new assets here", None, QtGui.QApplication.UnicodeUTF8))
        #self.baseName_lineEdit.setStatusTip(QtGui.QApplication.translate("Dialog", "enter the baseName for new assets here", None, QtGui.QApplication.UnicodeUTF8))
        #self.project_label.setText(QtGui.QApplication.translate("Dialog", "Project", None, QtGui.QApplication.UnicodeUTF8))
        #self.subName_lineEdit.setToolTip(QtGui.QApplication.translate("Dialog", "enter the subName for new assets here", None, QtGui.QApplication.UnicodeUTF8))
        #self.subName_lineEdit.setStatusTip(QtGui.QApplication.translate("Dialog", "enter the subName for new assets here", None, QtGui.QApplication.UnicodeUTF8))
        #self.user_comboBox1.setToolTip(QtGui.QApplication.translate("Dialog", "select your user initials", None, QtGui.QApplication.UnicodeUTF8))
        #self.user_comboBox1.setStatusTip(QtGui.QApplication.translate("Dialog", "select your user initials", None, QtGui.QApplication.UnicodeUTF8))
        #self.user_comboBox1.setWhatsThis(QtGui.QApplication.translate("Dialog", "User Initials:\n"
#"\n"
#"Select your user initials from the list, so anybody can understand who created this version of the asset...", None, QtGui.QApplication.UnicodeUTF8))
        #self.user_label1.setText(QtGui.QApplication.translate("Dialog", "User", None, QtGui.QApplication.UnicodeUTF8))
        #self.version_label1.setText(QtGui.QApplication.translate("Dialog", "Version", None, QtGui.QApplication.UnicodeUTF8))
        #self.formats_label.setText(QtGui.QApplication.translate("Dialog", "Format", None, QtGui.QApplication.UnicodeUTF8))

