# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ozgur/maya/scripts/oy-maya-scripts/oyTools/oyProjectManager/ui/assetManager.ui'
#
# Created: Mon Mar  8 16:24:12 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1002, 877)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_horizontalWidget = QtGui.QWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.main_horizontalWidget.sizePolicy().hasHeightForWidth())
        self.main_horizontalWidget.setSizePolicy(sizePolicy)
        self.main_horizontalWidget.setObjectName("main_horizontalWidget")
        self.main_horizontalLayout = QtGui.QHBoxLayout(self.main_horizontalWidget)
        self.main_horizontalLayout.setMargin(6)
        self.main_horizontalLayout.setObjectName("main_horizontalLayout")
        self.verticalWidget1 = QtGui.QWidget(self.main_horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.verticalWidget1.sizePolicy().hasHeightForWidth())
        self.verticalWidget1.setSizePolicy(sizePolicy)
        self.verticalWidget1.setObjectName("verticalWidget1")
        self.verticalLayout1 = QtGui.QVBoxLayout(self.verticalWidget1)
        self.verticalLayout1.setMargin(0)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.saveAsset_groupBox = QtGui.QGroupBox(self.verticalWidget1)
        self.saveAsset_groupBox.setObjectName("saveAsset_groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.saveAsset_groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridWidget1 = QtGui.QWidget(self.saveAsset_groupBox)
        self.gridWidget1.setObjectName("gridWidget1")
        self.gridLayout1 = QtGui.QGridLayout(self.gridWidget1)
        self.gridLayout1.setObjectName("gridLayout1")
        self.shot_label1 = QtGui.QLabel(self.gridWidget1)
        self.shot_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.shot_label1.setObjectName("shot_label1")
        self.gridLayout1.addWidget(self.shot_label1, 7, 0, 1, 1)
        self.server_label = QtGui.QLabel(self.gridWidget1)
        self.server_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.server_label.setObjectName("server_label")
        self.gridLayout1.addWidget(self.server_label, 0, 0, 1, 1)
        self.revision_label1 = QtGui.QLabel(self.gridWidget1)
        self.revision_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.revision_label1.setObjectName("revision_label1")
        self.gridLayout1.addWidget(self.revision_label1, 16, 0, 1, 1)
        self.version_horizontalWidget = QtGui.QWidget(self.gridWidget1)
        self.version_horizontalWidget.setObjectName("version_horizontalWidget")
        self.version_horizontalLayout = QtGui.QHBoxLayout(self.version_horizontalWidget)
        self.version_horizontalLayout.setMargin(0)
        self.version_horizontalLayout.setObjectName("version_horizontalLayout")
        self.version_spinBox = QtGui.QSpinBox(self.version_horizontalWidget)
        self.version_spinBox.setMinimum(1)
        self.version_spinBox.setMaximum(99999999)
        self.version_spinBox.setObjectName("version_spinBox")
        self.version_horizontalLayout.addWidget(self.version_spinBox)
        self.version_pushButton = QtGui.QPushButton(self.version_horizontalWidget)
        self.version_pushButton.setMinimumSize(QtCore.QSize(111, 0))
        self.version_pushButton.setObjectName("version_pushButton")
        self.version_horizontalLayout.addWidget(self.version_pushButton)
        self.gridLayout1.addWidget(self.version_horizontalWidget, 17, 1, 1, 1)
        self.shot_comboBox1 = QtGui.QComboBox(self.gridWidget1)
        self.shot_comboBox1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_comboBox1.sizePolicy().hasHeightForWidth())
        self.shot_comboBox1.setSizePolicy(sizePolicy)
        self.shot_comboBox1.setObjectName("shot_comboBox1")
        self.gridLayout1.addWidget(self.shot_comboBox1, 7, 1, 1, 1)
        self.sequence_label = QtGui.QLabel(self.gridWidget1)
        self.sequence_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sequence_label.setObjectName("sequence_label")
        self.gridLayout1.addWidget(self.sequence_label, 3, 0, 1, 1)
        self.subName_listWidget = QtGui.QListWidget(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.subName_listWidget.sizePolicy().hasHeightForWidth())
        self.subName_listWidget.setSizePolicy(sizePolicy)
        self.subName_listWidget.setAlternatingRowColors(True)
        self.subName_listWidget.setResizeMode(QtGui.QListView.Fixed)
        self.subName_listWidget.setObjectName("subName_listWidget")
        self.gridLayout1.addWidget(self.subName_listWidget, 13, 1, 1, 1)
        self.server_comboBox = QtGui.QComboBox(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.server_comboBox.sizePolicy().hasHeightForWidth())
        self.server_comboBox.setSizePolicy(sizePolicy)
        self.server_comboBox.setEditable(False)
        self.server_comboBox.setObjectName("server_comboBox")
        self.gridLayout1.addWidget(self.server_comboBox, 0, 1, 1, 1)
        self.note_lineEdit1 = QtGui.QLineEdit(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.note_lineEdit1.sizePolicy().hasHeightForWidth())
        self.note_lineEdit1.setSizePolicy(sizePolicy)
        self.note_lineEdit1.setObjectName("note_lineEdit1")
        self.gridLayout1.addWidget(self.note_lineEdit1, 19, 1, 1, 1)
        self.revision_horizontalWidget = QtGui.QWidget(self.gridWidget1)
        self.revision_horizontalWidget.setObjectName("revision_horizontalWidget")
        self.revision_horizontalLayout = QtGui.QHBoxLayout(self.revision_horizontalWidget)
        self.revision_horizontalLayout.setMargin(0)
        self.revision_horizontalLayout.setObjectName("revision_horizontalLayout")
        self.revision_spinBox = QtGui.QSpinBox(self.revision_horizontalWidget)
        self.revision_spinBox.setObjectName("revision_spinBox")
        self.revision_horizontalLayout.addWidget(self.revision_spinBox)
        self.revision_pushButton = QtGui.QPushButton(self.revision_horizontalWidget)
        self.revision_pushButton.setMinimumSize(QtCore.QSize(111, 0))
        self.revision_pushButton.setObjectName("revision_pushButton")
        self.revision_horizontalLayout.addWidget(self.revision_pushButton)
        self.gridLayout1.addWidget(self.revision_horizontalWidget, 16, 1, 1, 1)
        self.assetType_label1 = QtGui.QLabel(self.gridWidget1)
        self.assetType_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.assetType_label1.setObjectName("assetType_label1")
        self.gridLayout1.addWidget(self.assetType_label1, 6, 0, 1, 1)
        self.baseName_listWidget = QtGui.QListWidget(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.baseName_listWidget.sizePolicy().hasHeightForWidth())
        self.baseName_listWidget.setSizePolicy(sizePolicy)
        self.baseName_listWidget.setAlternatingRowColors(True)
        self.baseName_listWidget.setObjectName("baseName_listWidget")
        self.gridLayout1.addWidget(self.baseName_listWidget, 10, 1, 1, 1)
        self.assetType_comboBox1 = QtGui.QComboBox(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assetType_comboBox1.sizePolicy().hasHeightForWidth())
        self.assetType_comboBox1.setSizePolicy(sizePolicy)
        self.assetType_comboBox1.setObjectName("assetType_comboBox1")
        self.gridLayout1.addWidget(self.assetType_comboBox1, 6, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.gridWidget1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout1.addWidget(self.line_4, 12, 0, 1, 2)
        self.line = QtGui.QFrame(self.gridWidget1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout1.addWidget(self.line, 1, 0, 1, 2)
        self.project_comboBox = QtGui.QComboBox(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_comboBox.sizePolicy().hasHeightForWidth())
        self.project_comboBox.setSizePolicy(sizePolicy)
        self.project_comboBox.setEditable(False)
        self.project_comboBox.setObjectName("project_comboBox")
        self.gridLayout1.addWidget(self.project_comboBox, 2, 1, 1, 1)
        self.subName_label1 = QtGui.QLabel(self.gridWidget1)
        self.subName_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.subName_label1.setObjectName("subName_label1")
        self.gridLayout1.addWidget(self.subName_label1, 13, 0, 1, 1)
        self.note_label1 = QtGui.QLabel(self.gridWidget1)
        self.note_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.note_label1.setObjectName("note_label1")
        self.gridLayout1.addWidget(self.note_label1, 19, 0, 1, 1)
        self.baseName_label1 = QtGui.QLabel(self.gridWidget1)
        self.baseName_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.baseName_label1.setObjectName("baseName_label1")
        self.gridLayout1.addWidget(self.baseName_label1, 10, 0, 1, 1)
        self.sequence_comboBox = QtGui.QComboBox(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequence_comboBox.sizePolicy().hasHeightForWidth())
        self.sequence_comboBox.setSizePolicy(sizePolicy)
        self.sequence_comboBox.setEditable(False)
        self.sequence_comboBox.setObjectName("sequence_comboBox")
        self.gridLayout1.addWidget(self.sequence_comboBox, 3, 1, 1, 1)
        self.baseName_lineEdit = QtGui.QLineEdit(self.gridWidget1)
        self.baseName_lineEdit.setObjectName("baseName_lineEdit")
        self.gridLayout1.addWidget(self.baseName_lineEdit, 11, 1, 1, 1)
        self.project_label = QtGui.QLabel(self.gridWidget1)
        self.project_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.project_label.setObjectName("project_label")
        self.gridLayout1.addWidget(self.project_label, 2, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.gridWidget1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout1.addWidget(self.line_2, 4, 0, 1, 2)
        self.line_5 = QtGui.QFrame(self.gridWidget1)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout1.addWidget(self.line_5, 15, 0, 1, 2)
        self.line_3 = QtGui.QFrame(self.gridWidget1)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout1.addWidget(self.line_3, 8, 0, 1, 2)
        self.subName_lineEdit = QtGui.QLineEdit(self.gridWidget1)
        self.subName_lineEdit.setObjectName("subName_lineEdit")
        self.gridLayout1.addWidget(self.subName_lineEdit, 14, 1, 1, 1)
        self.user_comboBox1 = QtGui.QComboBox(self.gridWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_comboBox1.sizePolicy().hasHeightForWidth())
        self.user_comboBox1.setSizePolicy(sizePolicy)
        self.user_comboBox1.setObjectName("user_comboBox1")
        self.gridLayout1.addWidget(self.user_comboBox1, 18, 1, 1, 1)
        self.user_label1 = QtGui.QLabel(self.gridWidget1)
        self.user_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.user_label1.setObjectName("user_label1")
        self.gridLayout1.addWidget(self.user_label1, 18, 0, 1, 1)
        self.version_label1 = QtGui.QLabel(self.gridWidget1)
        self.version_label1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version_label1.setObjectName("version_label1")
        self.gridLayout1.addWidget(self.version_label1, 17, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.gridWidget1)
        self.saveButtons_horizontalWidget = QtGui.QWidget(self.saveAsset_groupBox)
        self.saveButtons_horizontalWidget.setObjectName("saveButtons_horizontalWidget")
        self.saveCanel_horizontalLayout = QtGui.QHBoxLayout(self.saveButtons_horizontalWidget)
        self.saveCanel_horizontalLayout.setObjectName("saveCanel_horizontalLayout")
        self.save_button = QtGui.QPushButton(self.saveButtons_horizontalWidget)
        self.save_button.setObjectName("save_button")
        self.saveCanel_horizontalLayout.addWidget(self.save_button)
        self.export_button = QtGui.QPushButton(self.saveButtons_horizontalWidget)
        self.export_button.setObjectName("export_button")
        self.saveCanel_horizontalLayout.addWidget(self.export_button)
        self.verticalLayout_3.addWidget(self.saveButtons_horizontalWidget)
        self.verticalLayout1.addWidget(self.saveAsset_groupBox)
        self.main_horizontalLayout.addWidget(self.verticalWidget1)
        self.verticalWidget2 = QtGui.QWidget(self.main_horizontalWidget)
        self.verticalWidget2.setObjectName("verticalWidget2")
        self.verticalLayout2 = QtGui.QVBoxLayout(self.verticalWidget2)
        self.verticalLayout2.setMargin(0)
        self.verticalLayout2.setObjectName("verticalLayout2")
        self.shotData_groupBox = QtGui.QGroupBox(self.verticalWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.shotData_groupBox.sizePolicy().hasHeightForWidth())
        self.shotData_groupBox.setSizePolicy(sizePolicy)
        self.shotData_groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.shotData_groupBox.setObjectName("shotData_groupBox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.shotData_groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalWidget = QtGui.QWidget(self.shotData_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frameRange_label = QtGui.QLabel(self.horizontalWidget)
        self.frameRange_label.setObjectName("frameRange_label")
        self.horizontalLayout_2.addWidget(self.frameRange_label)
        self.line_7 = QtGui.QFrame(self.horizontalWidget)
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_2.addWidget(self.line_7)
        self.startFrame_label = QtGui.QLabel(self.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startFrame_label.sizePolicy().hasHeightForWidth())
        self.startFrame_label.setSizePolicy(sizePolicy)
        self.startFrame_label.setObjectName("startFrame_label")
        self.horizontalLayout_2.addWidget(self.startFrame_label)
        self.startFrame_spinBox = QtGui.QSpinBox(self.horizontalWidget)
        self.startFrame_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startFrame_spinBox.sizePolicy().hasHeightForWidth())
        self.startFrame_spinBox.setSizePolicy(sizePolicy)
        self.startFrame_spinBox.setMaximum(999999999)
        self.startFrame_spinBox.setObjectName("startFrame_spinBox")
        self.horizontalLayout_2.addWidget(self.startFrame_spinBox)
        self.endFrame_label = QtGui.QLabel(self.horizontalWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endFrame_label.sizePolicy().hasHeightForWidth())
        self.endFrame_label.setSizePolicy(sizePolicy)
        self.endFrame_label.setObjectName("endFrame_label")
        self.horizontalLayout_2.addWidget(self.endFrame_label)
        self.endFrame_spinBox = QtGui.QSpinBox(self.horizontalWidget)
        self.endFrame_spinBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endFrame_spinBox.sizePolicy().hasHeightForWidth())
        self.endFrame_spinBox.setSizePolicy(sizePolicy)
        self.endFrame_spinBox.setMaximum(999999999)
        self.endFrame_spinBox.setObjectName("endFrame_spinBox")
        self.horizontalLayout_2.addWidget(self.endFrame_spinBox)
        self.verticalLayout_2.addWidget(self.horizontalWidget)
        self.shotDescription_label = QtGui.QLabel(self.shotData_groupBox)
        self.shotDescription_label.setObjectName("shotDescription_label")
        self.verticalLayout_2.addWidget(self.shotDescription_label)
        self.shotDescription_textEdit = QtGui.QTextEdit(self.shotData_groupBox)
        self.shotDescription_textEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.shotDescription_textEdit.sizePolicy().hasHeightForWidth())
        self.shotDescription_textEdit.setSizePolicy(sizePolicy)
        self.shotDescription_textEdit.setObjectName("shotDescription_textEdit")
        self.verticalLayout_2.addWidget(self.shotDescription_textEdit)
        self.verticalLayout2.addWidget(self.shotData_groupBox)
        self.open_groupBox = QtGui.QGroupBox(self.verticalWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.open_groupBox.sizePolicy().hasHeightForWidth())
        self.open_groupBox.setSizePolicy(sizePolicy)
        self.open_groupBox.setObjectName("open_groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.open_groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalWidget_2 = QtGui.QWidget(self.open_groupBox)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.showLastNEntry_checkBox = QtGui.QCheckBox(self.horizontalWidget_2)
        self.showLastNEntry_checkBox.setChecked(True)
        self.showLastNEntry_checkBox.setObjectName("showLastNEntry_checkBox")
        self.horizontalLayout.addWidget(self.showLastNEntry_checkBox)
        self.numberOfEntry_spinBox = QtGui.QSpinBox(self.horizontalWidget_2)
        self.numberOfEntry_spinBox.setMinimum(1)
        self.numberOfEntry_spinBox.setMaximum(9999999)
        self.numberOfEntry_spinBox.setObjectName("numberOfEntry_spinBox")
        self.horizontalLayout.addWidget(self.numberOfEntry_spinBox)
        self.label = QtGui.QLabel(self.horizontalWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.horizontalWidget_2)
        self.assets_tableWidget1 = QtGui.QTableWidget(self.open_groupBox)
        self.assets_tableWidget1.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.assets_tableWidget1.setAlternatingRowColors(True)
        self.assets_tableWidget1.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.assets_tableWidget1.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.assets_tableWidget1.setShowGrid(False)
        self.assets_tableWidget1.setGridStyle(QtCore.Qt.NoPen)
        self.assets_tableWidget1.setColumnCount(3)
        self.assets_tableWidget1.setObjectName("assets_tableWidget1")
        self.assets_tableWidget1.setColumnCount(3)
        self.assets_tableWidget1.setRowCount(0)
        self.assets_tableWidget1.horizontalHeader().setStretchLastSection(True)
        self.assets_tableWidget1.verticalHeader().setVisible(False)
        self.assets_tableWidget1.verticalHeader().setDefaultSectionSize(19)
        self.verticalLayout_4.addWidget(self.assets_tableWidget1)
        self.openButtons_horizontalWidget = QtGui.QWidget(self.open_groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openButtons_horizontalWidget.sizePolicy().hasHeightForWidth())
        self.openButtons_horizontalWidget.setSizePolicy(sizePolicy)
        self.openButtons_horizontalWidget.setObjectName("openButtons_horizontalWidget")
        self.openButtons_horizontalLayout = QtGui.QHBoxLayout(self.openButtons_horizontalWidget)
        self.openButtons_horizontalLayout.setObjectName("openButtons_horizontalLayout")
        self.open_button = QtGui.QPushButton(self.openButtons_horizontalWidget)
        self.open_button.setObjectName("open_button")
        self.openButtons_horizontalLayout.addWidget(self.open_button)
        self.reference_button = QtGui.QPushButton(self.openButtons_horizontalWidget)
        self.reference_button.setObjectName("reference_button")
        self.openButtons_horizontalLayout.addWidget(self.reference_button)
        self.import_button = QtGui.QPushButton(self.openButtons_horizontalWidget)
        self.import_button.setObjectName("import_button")
        self.openButtons_horizontalLayout.addWidget(self.import_button)
        self.close_button = QtGui.QPushButton(self.openButtons_horizontalWidget)
        self.close_button.setObjectName("close_button")
        self.openButtons_horizontalLayout.addWidget(self.close_button)
        self.verticalLayout_4.addWidget(self.openButtons_horizontalWidget)
        self.verticalLayout2.addWidget(self.open_groupBox)
        self.main_horizontalLayout.addWidget(self.verticalWidget2)
        self.verticalLayout.addWidget(self.main_horizontalWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Asset Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAsset_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Save Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_label1.setText(QtGui.QApplication.translate("Dialog", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.server_label.setText(QtGui.QApplication.translate("Dialog", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.revision_label1.setText(QtGui.QApplication.translate("Dialog", "Revision", None, QtGui.QApplication.UnicodeUTF8))
        self.version_spinBox.setToolTip(QtGui.QApplication.translate("Dialog", "it is automatically increased by 1", None, QtGui.QApplication.UnicodeUTF8))
        self.version_spinBox.setStatusTip(QtGui.QApplication.translate("Dialog", "it is automatically increased by 1", None, QtGui.QApplication.UnicodeUTF8))
        self.version_spinBox.setWhatsThis(QtGui.QApplication.translate("Dialog", "Version Number:\n"
"\n"
"Any incarnation of an asset should be have different version numbers.", None, QtGui.QApplication.UnicodeUTF8))
        self.version_pushButton.setToolTip(QtGui.QApplication.translate("Dialog", "gets the latest version number", None, QtGui.QApplication.UnicodeUTF8))
        self.version_pushButton.setStatusTip(QtGui.QApplication.translate("Dialog", "gets the latest version number", None, QtGui.QApplication.UnicodeUTF8))
        self.version_pushButton.setText(QtGui.QApplication.translate("Dialog", "Latest Version", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_comboBox1.setToolTip(QtGui.QApplication.translate("Dialog", "if the type is a shot dependent type this will be activated", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_comboBox1.setStatusTip(QtGui.QApplication.translate("Dialog", "if the type is a shot dependent type this will be activated", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_comboBox1.setWhatsThis(QtGui.QApplication.translate("Dialog", "Shot:\n"
"\n"
"If an asset is shot dependent, its base name is a shot string (SH001, SH010 etc. ). So, shot and base name comboBoxes are actually showing the base name of the asset, but it lets the user to separate the shot dependent asset types from shot independent types.", None, QtGui.QApplication.UnicodeUTF8))
        self.sequence_label.setText(QtGui.QApplication.translate("Dialog", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.subName_listWidget.setToolTip(QtGui.QApplication.translate("Dialog", "displays the subNames of the current asset", None, QtGui.QApplication.UnicodeUTF8))
        self.subName_listWidget.setStatusTip(QtGui.QApplication.translate("Dialog", "displays the subNames of the current asset", None, QtGui.QApplication.UnicodeUTF8))
        self.server_comboBox.setToolTip(QtGui.QApplication.translate("Dialog", "Select a Server", None, QtGui.QApplication.UnicodeUTF8))
        self.server_comboBox.setStatusTip(QtGui.QApplication.translate("Dialog", "Select a Server", None, QtGui.QApplication.UnicodeUTF8))
        self.server_comboBox.setWhatsThis(QtGui.QApplication.translate("Dialog", "Server:\n"
"\n"
"Servers are the places that the main project folders are saved. For now there is only one supported server. In the future that can be expanded to multiple servers...", None, QtGui.QApplication.UnicodeUTF8))
        self.note_lineEdit1.setToolTip(QtGui.QApplication.translate("Dialog", "it is a limited field, try to keep it brief", None, QtGui.QApplication.UnicodeUTF8))
        self.note_lineEdit1.setStatusTip(QtGui.QApplication.translate("Dialog", "it is a limited field, try to keep it brief", None, QtGui.QApplication.UnicodeUTF8))
        self.note_lineEdit1.setWhatsThis(QtGui.QApplication.translate("Dialog", "Note:\n"
"\n"
"You can use this field to leave little but important messages here... It is limited with 30 characters...", None, QtGui.QApplication.UnicodeUTF8))
        self.revision_spinBox.setToolTip(QtGui.QApplication.translate("Dialog", "increase it when the asset needs a revision", None, QtGui.QApplication.UnicodeUTF8))
        self.revision_spinBox.setStatusTip(QtGui.QApplication.translate("Dialog", "increase it when the asset needs a revision", None, QtGui.QApplication.UnicodeUTF8))
        self.revision_spinBox.setWhatsThis(QtGui.QApplication.translate("Dialog", "Revision Number:\n"
"\n"
"Revision numbers represents the milestones in the development of this asset. Generally it is increased when something big is changed in the asset.", None, QtGui.QApplication.UnicodeUTF8))
        self.revision_pushButton.setToolTip(QtGui.QApplication.translate("Dialog", "gets the latest revision number", None, QtGui.QApplication.UnicodeUTF8))
        self.revision_pushButton.setStatusTip(QtGui.QApplication.translate("Dialog", "gets the latest revision number", None, QtGui.QApplication.UnicodeUTF8))
        self.revision_pushButton.setText(QtGui.QApplication.translate("Dialog", "Lastest Revision", None, QtGui.QApplication.UnicodeUTF8))
        self.assetType_label1.setText(QtGui.QApplication.translate("Dialog", "Asset Type", None, QtGui.QApplication.UnicodeUTF8))
        self.baseName_listWidget.setToolTip(QtGui.QApplication.translate("Dialog", "displays the baseNames of the current assetType", None, QtGui.QApplication.UnicodeUTF8))
        self.baseName_listWidget.setStatusTip(QtGui.QApplication.translate("Dialog", "displays the baseNames of the current assetType", None, QtGui.QApplication.UnicodeUTF8))
        self.assetType_comboBox1.setToolTip(QtGui.QApplication.translate("Dialog", "Select an asset type", None, QtGui.QApplication.UnicodeUTF8))
        self.assetType_comboBox1.setStatusTip(QtGui.QApplication.translate("Dialog", "Select an asset type", None, QtGui.QApplication.UnicodeUTF8))
        self.assetType_comboBox1.setWhatsThis(QtGui.QApplication.translate("Dialog", "Asset Type:\n"
"\n"
"Assets has types that lets you distinguish their purpose of existance. This comboBox lists the asset types that the sequence and the current host environment (MAYA, NUKE etc.) can support.", None, QtGui.QApplication.UnicodeUTF8))
        self.project_comboBox.setToolTip(QtGui.QApplication.translate("Dialog", "Select a Project", None, QtGui.QApplication.UnicodeUTF8))
        self.project_comboBox.setStatusTip(QtGui.QApplication.translate("Dialog", "Select a Project", None, QtGui.QApplication.UnicodeUTF8))
        self.project_comboBox.setWhatsThis(QtGui.QApplication.translate("Dialog", "Project:\n"
"\n"
"A project is a collection of sequences. So projects can only contain sequences. This comboBox lists the current projects on the server. If you select one it will update the available sequences for that project...", None, QtGui.QApplication.UnicodeUTF8))
        self.subName_label1.setText(QtGui.QApplication.translate("Dialog", "Sub Name", None, QtGui.QApplication.UnicodeUTF8))
        self.note_label1.setText(QtGui.QApplication.translate("Dialog", "Note", None, QtGui.QApplication.UnicodeUTF8))
        self.baseName_label1.setText(QtGui.QApplication.translate("Dialog", "Base Name", None, QtGui.QApplication.UnicodeUTF8))
        self.sequence_comboBox.setToolTip(QtGui.QApplication.translate("Dialog", "Select a Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.sequence_comboBox.setStatusTip(QtGui.QApplication.translate("Dialog", "Select a Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.sequence_comboBox.setWhatsThis(QtGui.QApplication.translate("Dialog", "Sequence:\n"
"\n"
"Sequences are collections of folders. Each folder has a special meaning and can may contain one type of asset file. Every sequence has its own settings. So while one sequence supports some features, others may not...", None, QtGui.QApplication.UnicodeUTF8))
        self.baseName_lineEdit.setToolTip(QtGui.QApplication.translate("Dialog", "enter the baseName for new assets here", None, QtGui.QApplication.UnicodeUTF8))
        self.baseName_lineEdit.setStatusTip(QtGui.QApplication.translate("Dialog", "enter the baseName for new assets here", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label.setText(QtGui.QApplication.translate("Dialog", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.subName_lineEdit.setToolTip(QtGui.QApplication.translate("Dialog", "enter the subName for new assets here", None, QtGui.QApplication.UnicodeUTF8))
        self.subName_lineEdit.setStatusTip(QtGui.QApplication.translate("Dialog", "enter the subName for new assets here", None, QtGui.QApplication.UnicodeUTF8))
        self.user_comboBox1.setToolTip(QtGui.QApplication.translate("Dialog", "select your user initials", None, QtGui.QApplication.UnicodeUTF8))
        self.user_comboBox1.setStatusTip(QtGui.QApplication.translate("Dialog", "select your user initials", None, QtGui.QApplication.UnicodeUTF8))
        self.user_comboBox1.setWhatsThis(QtGui.QApplication.translate("Dialog", "User Initials:\n"
"\n"
"Select your user initials from the list, so anybody can understand who created this version of the asset...", None, QtGui.QApplication.UnicodeUTF8))
        self.user_label1.setText(QtGui.QApplication.translate("Dialog", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.version_label1.setText(QtGui.QApplication.translate("Dialog", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setToolTip(QtGui.QApplication.translate("Dialog", "Saves the asset to the server", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setStatusTip(QtGui.QApplication.translate("Dialog", "Saves the asset to the server", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setWhatsThis(QtGui.QApplication.translate("Dialog", "Save:\n"
"\n"
"Saves the asset to the server", None, QtGui.QApplication.UnicodeUTF8))
        self.save_button.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.export_button.setToolTip(QtGui.QApplication.translate("Dialog", "Exports the Selected items as a new asset", None, QtGui.QApplication.UnicodeUTF8))
        self.export_button.setStatusTip(QtGui.QApplication.translate("Dialog", "Exports the Selected items as a new asset", None, QtGui.QApplication.UnicodeUTF8))
        self.export_button.setWhatsThis(QtGui.QApplication.translate("Dialog", "Export:\n"
"\n"
"Exports the selected content to the server as an asset", None, QtGui.QApplication.UnicodeUTF8))
        self.export_button.setText(QtGui.QApplication.translate("Dialog", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.shotData_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Shot Data", None, QtGui.QApplication.UnicodeUTF8))
        self.frameRange_label.setText(QtGui.QApplication.translate("Dialog", "Frame Range", None, QtGui.QApplication.UnicodeUTF8))
        self.startFrame_label.setText(QtGui.QApplication.translate("Dialog", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.endFrame_label.setText(QtGui.QApplication.translate("Dialog", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.shotDescription_label.setText(QtGui.QApplication.translate("Dialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.open_groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Open Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.showLastNEntry_checkBox.setToolTip(QtGui.QApplication.translate("Dialog", "if checked, the list below shows maximum n number of items, the n is defined in the next spinB,ox", None, QtGui.QApplication.UnicodeUTF8))
        self.showLastNEntry_checkBox.setStatusTip(QtGui.QApplication.translate("Dialog", "maximum number of entry to view", None, QtGui.QApplication.UnicodeUTF8))
        self.showLastNEntry_checkBox.setText(QtGui.QApplication.translate("Dialog", "Show Last", None, QtGui.QApplication.UnicodeUTF8))
        self.numberOfEntry_spinBox.setStatusTip(QtGui.QApplication.translate("Dialog", "maximum number of entry to view", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setStatusTip(QtGui.QApplication.translate("Dialog", "maximum number of entry to view", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "entry", None, QtGui.QApplication.UnicodeUTF8))
        self.open_button.setToolTip(QtGui.QApplication.translate("Dialog", "Opens the selected asset", None, QtGui.QApplication.UnicodeUTF8))
        self.open_button.setStatusTip(QtGui.QApplication.translate("Dialog", "Opens the selected asset", None, QtGui.QApplication.UnicodeUTF8))
        self.open_button.setWhatsThis(QtGui.QApplication.translate("Dialog", "Open:\n"
"\n"
"Opens the current selected asset in the host application", None, QtGui.QApplication.UnicodeUTF8))
        self.open_button.setText(QtGui.QApplication.translate("Dialog", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.reference_button.setToolTip(QtGui.QApplication.translate("Dialog", "References the asset tho the current scene (Maya only)", None, QtGui.QApplication.UnicodeUTF8))
        self.reference_button.setStatusTip(QtGui.QApplication.translate("Dialog", "References the asset tho the current scene (Maya only)", None, QtGui.QApplication.UnicodeUTF8))
        self.reference_button.setWhatsThis(QtGui.QApplication.translate("Dialog", "Reference:\n"
"\n"
"References the asset to the current environment in the host application. For now just MAYA supports referencing, but in near future NUKE will have too...", None, QtGui.QApplication.UnicodeUTF8))
        self.reference_button.setText(QtGui.QApplication.translate("Dialog", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.import_button.setToolTip(QtGui.QApplication.translate("Dialog", "Imports the contents to the current scene", None, QtGui.QApplication.UnicodeUTF8))
        self.import_button.setStatusTip(QtGui.QApplication.translate("Dialog", "Imports the contents to the current scene", None, QtGui.QApplication.UnicodeUTF8))
        self.import_button.setWhatsThis(QtGui.QApplication.translate("Dialog", "Import:\n"
"\n"
"Imports the content of the selected asset to the current environment in the host application...", None, QtGui.QApplication.UnicodeUTF8))
        self.import_button.setText(QtGui.QApplication.translate("Dialog", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setToolTip(QtGui.QApplication.translate("Dialog", "Quits without doing anything", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setStatusTip(QtGui.QApplication.translate("Dialog", "Quits without doing anything", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setWhatsThis(QtGui.QApplication.translate("Dialog", "Cancel:\n"
"\n"
"Just quits the application without doing anything", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setText(QtGui.QApplication.translate("Dialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

